### ISSUE TITLE
SUMMARY: Meets Expectations

### ISSUE THREAD

**Issue by jzhu01** [JaimyAlexander/prj-rev-bwfs-dasmoto#5]
Great job on this project! I really liked your usage of divs in your code, and how clean and easy to read your code was. In terms of improvement, I recommend setting the font-family once to avoid repetition and using classes instead of IDs for the spans.

If you’re in the mood for a challenge...I would look into adding more items under each section and finding a nice way to lay them out. Here's a link to get you started - https://www.w3schools.com/css/css_rwd_grid.asp. Keep up the nice work! ^_^

**Comment by JaimyAlexander** [comment]
Thank you very much for your thorough feedback and advice, will certainly keep it in mind for next projects. And will most definitely look into the Grid View!
